# Versão do Docker Compose
version: "3.8"

# Inicia os serviços do containers
services:

  wordpress: 
    # Características do Container
    container_name: wordpress
    image: wordpress
    environment:
      - WORDPRESS_DB_PASSWORD=123456
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - 8088:80
    volumes: 
      - ./html:/var/www/html
    links:
      - database
  database: 
    container_name: database
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./database:/var/lib/mysql

