# Use a imagem base do Alpine Linux
FROM alpine:latest

# Adicione um usuário não-root chamado 'app'
RUN adduser -D -g '' app

# Configure o usuário padrão para 'app'
USER app

# Restante do Dockerfile...